---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:C://Users//I509703//IdeaProjects//transactions-test-java-cap//sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
cds:
  datasource:
    auto-config.enabled: false

server:
  port: 12000

